services:
  db:
    image: postgres:15
    container_name: postgres_local
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=GSST
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data

volumes:
  postgres_data_local: